# Generated by Django 3.0.9 on 2020-12-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0004_auto_20201130_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='zorg',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='zorg/advertisment_images/'),
        ),
    ]
