# Generated by Django 3.0.9 on 2020-12-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0005_auto_20201130_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='photo_1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='photo_2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='photo_3',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='photo_4',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='photo_5',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
    ]
