# Generated by Django 3.0.9 on 2020-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0006_auto_20201201_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='photo_10',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_6',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_7',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_8',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
        migrations.AddField(
            model_name='advertisment',
            name='photo_9',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='advertisment_images/'),
        ),
    ]
