# Generated by Django 3.0.9 on 2020-12-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0007_auto_20201201_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='photo_10',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='photo_8',
        ),
        migrations.RemoveField(
            model_name='advertisment',
            name='photo_9',
        ),
    ]
