# Generated by Django 3.0.9 on 2020-12-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0002_auto_20201201_0335'),
        ('v3', '0009_auto_20201201_0246'),
    ]

    operations = [
    ]
